
height: 539
width: 504
frameborder: 0
allowfullscreen: true

linkedin_posts:

  #2024
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:7201316253427195905"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:7187927391619448834"
  - "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7160376742572871680"

  #2023
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:7119067456064651264"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:7113016917593919489"
  - "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7108901283373203456"
  - "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7108899440794484736"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:7105338310427906048"
  - "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7104750710583410688"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:7096598256368955392"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:7096598256368955392"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:7088234296976572417"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:7088216295988498432"
  - "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7083199979015602177"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:7081868067491745792"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:7078632096717574144"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:7042398038497116160"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:7018726681049792512"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:6953788922996948992"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:6953050478297432064"


  #2022
  - "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:6945568690117513216"

  # 2021
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:6753535468706648064"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:6747671275528953856"
  - "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:6747426492319449088"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:6725116187497385984"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:6688547757021642752"



  # 2020
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:6683926912794025985"
  - "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:6664396348709707776"
  - "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:6654556393464442880"
  - "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:6650602950106333184"
  - "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:6650600517435174912"
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:6604093973868883968"

  # 2019
  - "https://www.linkedin.com/embed/feed/update/urn:li:share:6534747106031218688/"

